test_list1=input("enter the list 1:")
test_list2=input("enter the list 2:")
print("the list 1 is:"+str(test_list1))
print("the list 2 is:"+str(test_list2))
res=sorted(test_list1+test_list2)
print("the combined sorted list is :"+str(res))
